// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniversityManagementSystem.DLL.DbContext;

#nullable disable

namespace UniversityManagementSystem.DLL.Migrations;

[DbContext(typeof(ApplicationDbContext))]
partial class ApplicationDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.8")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("UniversityManagementSystem.DLL.Models.Category", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ShortName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Categories");
            });

        modelBuilder.Entity("UniversityManagementSystem.DLL.Models.CategoryProduct", b =>
            {
                b.Property<int>("ProductId")
                    .HasColumnType("int");

                b.Property<int>("CategoryId")
                    .HasColumnType("int");

                b.HasKey("ProductId", "CategoryId");

                b.HasIndex("CategoryId");

                b.ToTable("CategoryProducts");
            });

        modelBuilder.Entity("UniversityManagementSystem.DLL.Models.Product", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<double>("Price")
                    .HasColumnType("float");

                b.HasKey("Id");

                b.ToTable("Products");
            });

        modelBuilder.Entity("UniversityManagementSystem.DLL.Models.CategoryProduct", b =>
            {
                b.HasOne("UniversityManagementSystem.DLL.Models.Category", "Category")
                    .WithMany("CategoryProducts")
                    .HasForeignKey("CategoryId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("UniversityManagementSystem.DLL.Models.Product", "Product")
                    .WithMany("CategoryProducts")
                    .HasForeignKey("ProductId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Category");

                b.Navigation("Product");
            });

        modelBuilder.Entity("UniversityManagementSystem.DLL.Models.Category", b =>
            {
                b.Navigation("CategoryProducts");
            });

        modelBuilder.Entity("UniversityManagementSystem.DLL.Models.Product", b =>
            {
                b.Navigation("CategoryProducts");
            });
#pragma warning restore 612, 618
    }
}
